version: '3.9'
services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    expose:
      - 6000
    ports:
      - 6000:6000
    command: -p 6000
    environment:
      POSTGRES_USER: trainum_user
      POSTGRES_PASSWORD: trainum
      POSTGRES_DB: trainum_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  postgres-test:
    image: postgres:latest
    build:
      cache_from:
        - postgres-dev
    container_name: postgres-test
    depends_on:
      - postgres-dev
    expose:
      - 6001
    ports:
      - 6001:6001
    command: -p 6001
    environment:
      POSTGRES_USER: trainum_test_user
      POSTGRES_PASSWORD: trainum
      POSTGRES_DB: trainum_test_db
    restart: unless-stopped
  trainum:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 9090:9090
    volumes:
      - ./dist/apps/trainum:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    stdin_open: true
    volumes:
      - ./dist/apps/api:/app
      - /app/node_modules
      - /app/prisma
    links:
      - postgres-dev
      - postgres-test
    environment:
      DATABASE_URL: postgresql://trainum_user:trainum@postgres:6000/trainum_db?schema=public?connect_timeout=300
      JWT_AT_SECRET: alvialvi
      JWT_RT_SECRET: alvialvi
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    depends_on:
      - postgres-dev
      - postgres-test
    ports:
      - '3333:3333'
    restart: unless-stopped

volumes:
  postgres-data:
