FROM node:16-alpine

WORKDIR /app

RUN npm install -g nodemon
  
# generated prisma files
COPY apps/api/prisma ./prisma/


# COPY
COPY dist/apps/api .

RUN npm install

RUN npx prisma migrate dev

RUN npx prisma generate

EXPOSE 3333

# A command to start the server
CMD ["nodemon", "-L" ,"main.js"]