import { Exercise } from '../entities';

export const ExercisesSeed = (): Exercise[] => {
  return [
    {
      name: 'Bench Press',
      description: 'Chest Exercise',
      type: 'weighted',
      targets: [{ name: 'chest' }, { name: 'shoulders' }],
      images: [],
      equipment: [{ name: 'barbell' }, { name: 'bench' }],
    },
    {
      name: 'Deadlift',
      description: 'Legs Exercise',
      type: 'weighted',
      targets: [{ name: 'back' }, { name: 'legs' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Squat',
      description: 'Legs Exercise',
      type: 'weighted',
      targets: [{ name: 'back' }, { name: 'legs' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Overhead Press',
      description: 'Shoulders Exercise',
      type: 'weighted',
      targets: [{ name: 'shoulders' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Bicep Curl',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Tricep Pushdown',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Cable Crossover',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'cable' }],
      images: [],
    },
    {
      name: 'Cable Curl',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'cable' }],
      images: [],
    },
    {
      name: 'Cable Row',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'cable' }],
      images: [],
    },
    {
      name: 'Cable Pullover',
      description: 'Arms Exercise',
      type: 'weighted',
      targets: [{ name: 'arms' }],
      equipment: [{ name: 'cable' }],
      images: [],
    },
    {
      name: 'Plank',
      description: 'Core Exercise',
      type: 'weighted',
      targets: [{ name: 'core' }],
      equipment: [{ name: 'none' }],
      images: [],
    },
    {
      name: 'Leg Press',
      description: 'Legs Exercise',
      type: 'weighted',
      targets: [{ name: 'back' }, { name: 'legs' }],
      equipment: [{ name: 'barbell' }],
      images: [],
    },
    {
      name: 'Running',
      description: 'Core Exercise',
      type: 'weighted',
      targets: [{ name: 'core' }, { name: 'cardio' }],
      equipment: [{ name: 'treadmill' }],
      images: [],
    },
  ];
};
